/**
 * THE RIVALS' VOICES (0.23.1, Andy): "use my ElevenLabs for the narrator
 * voice, the default AI voice is not good. Try to give some cheeky English
 * accents to the enemies."
 *
 * The thirty lines of trash talk are RECORDED ONCE, through Andy's own
 * ElevenLabs account, in a few British voices, by tools/voice-lines.ts;
 * the clips ship as static files under public/voice/<slug>/<n>.mp3, so
 * no key ever reaches the browser, nothing is spoken at run time by a
 * machine voice, and a clip plays offline once it has been heard. Each
 * monster keeps ONE voice for good (its id hashes to one of the slugs),
 * so a rival sounds the same every time it turns up.
 *
 * VOICES is written by the generator; it is empty until the clips exist,
 * and then the static law in voices.test.ts holds every slug to all
 * thirty lines.
 */

import { TRASH_TALK } from "./duel";

export interface Voice {
  /** The folder under public/voice, and the app's name for the voice. */
  readonly slug: string;
  /** The ElevenLabs voice it was recorded with, for the record. */
  readonly name: string;
  readonly accent: string;
}

// GENERATED by tools/voice-lines.ts. Do not edit by hand.
export const VOICES: readonly Voice[] = [
  { slug: "george", name: "George", accent: "british" },
  { slug: "alice", name: "Alice", accent: "british" },
  { slug: "daniel", name: "Daniel", accent: "british" },
  { slug: "lily", name: "Lily", accent: "british" },
];

/** One voice per monster, for good. Null while no clips exist. */
export const voiceFor = (creatureId: string): Voice | null => {
  if (VOICES.length === 0) return null;
  let h = 7;
  for (const ch of creatureId) h = (Math.imul(h, 31) + ch.charCodeAt(0)) >>> 0;
  return VOICES[h % VOICES.length]!;
};

/** Where a line's clip lives: the line's index in TRASH_TALK. */
export const voiceUrl = (v: Voice, line: string): string | null => {
  const i = TRASH_TALK.indexOf(line);
  return i < 0 ? null : `/voice/${v.slug}/${i}.mp3`;
};
