// App icons, drawn rather than generated by a model.
//
// The house scar: generated icons come back with a background card baked in
// however firmly the prompt forbids it, and per-file alpha metrics all pass
// while the contact sheet finds it in three seconds. Drawing the mark in SVG
// and screenshotting it removes that entire failure class.
//
// TWO SETS, per the PWA icon law. `any` is the normal mark; `maskable` is
// FULL BLEED opaque with the art inside the 80% safe circle, because Chrome
// only cuts its squircle from icons marked maskable and letterboxes the rest
// in a white box.
import { chromium } from "playwright";
import { mkdirSync } from "node:fs";

const OUT = new URL("../public/icons/", import.meta.url).pathname;
mkdirSync(OUT, { recursive: true });

// A monster jaw biting a skate deck. Heavy outline, flat saturated fill.
const mark = (inset) => `
<g transform="translate(256 256) scale(${inset}) translate(-256 -256)">
  <path d="M96 300 C60 300 60 372 96 372 L416 372 C452 372 452 300 416 300 Z"
        fill="#B6FF3C" stroke="#05070A" stroke-width="22" stroke-linejoin="round"/>
  <circle cx="160" cy="398" r="30" fill="#05070A"/>
  <circle cx="352" cy="398" r="30" fill="#05070A"/>
  <path d="M120 300 C120 160 250 96 330 140 C300 170 292 214 316 244 C356 236 386 262 386 300 Z"
        fill="#FF3D8B" stroke="#05070A" stroke-width="22" stroke-linejoin="round"/>
  <circle cx="214" cy="216" r="34" fill="#FFFFFF" stroke="#05070A" stroke-width="18"/>
  <circle cx="222" cy="224" r="14" fill="#05070A"/>
  <path d="M150 292 l24 -40 l24 40 z" fill="#FFFFFF" stroke="#05070A" stroke-width="10" stroke-linejoin="round"/>
  <path d="M214 292 l24 -40 l24 40 z" fill="#FFFFFF" stroke="#05070A" stroke-width="10" stroke-linejoin="round"/>
  <path d="M278 292 l24 -40 l24 40 z" fill="#FFFFFF" stroke="#05070A" stroke-width="10" stroke-linejoin="round"/>
</g>`;

const page1 = (maskable) => `<!doctype html><html><body style="margin:0">
<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512" viewBox="0 0 512 512">
  <defs><radialGradient id="bg" cx="50%" cy="38%" r="72%">
    <stop offset="0" stop-color="#1B2430"/><stop offset="1" stop-color="#07090C"/>
  </radialGradient></defs>
  ${maskable
    ? `<rect width="512" height="512" fill="url(#bg)"/>`
    : `<rect x="26" y="26" width="460" height="460" rx="104" fill="url(#bg)" stroke="#05070A" stroke-width="16"/>`}
  ${mark(maskable ? 0.74 : 0.9)}
</svg></body></html>`;

const browser = await chromium.launch();
for (const [name, maskable, sizes] of [["icon", false, [180, 192, 512]], ["icon", true, [192, 512]]]) {
  for (const size of sizes) {
    const page = await browser.newPage({ viewport: { width: size, height: size }, deviceScaleFactor: 1 });
    await page.setContent(page1(maskable));
    await page.addStyleTag({ content: `svg{width:${size}px;height:${size}px;display:block}` });
    const file = `${OUT}${name}-${size}${maskable ? "-maskable" : ""}.png`;
    await page.screenshot({ path: file, omitBackground: !maskable });
    await page.close();
    console.log("wrote", file.split("/").slice(-1)[0]);
  }
}
await browser.close();
